base_url = "https://www.jamespking.com"
title = "Notes"
description = "JPK's notes and writings"
default_language = "en"

compile_sass = false
minify_html = true
build_search_index = false

taxonomies = [
    { name = "tags", feed = true },
]

[markdown]
smart_punctuation = true

[markdown.highlighting]
theme = "catppuccin-mocha"
style = "inline"

[extra]
author = "JPK"
